language: cpp
compiler: gcc
sudo: require
dist: focal

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt-5.14.2-focal -y
  - sudo apt-get update -q

install:
  - sudo apt-get -y install qt514base qt514svg libgl1-mesa-dev libssl-dev zlib1g-dev ruby patchelf automake
  - source /opt/qt*/bin/qt*-env.sh

script:
  - export PATH=./packaging/continuous-x86_64:$PATH
  - ruby prepare.rb
  - mkdir -p _bin/ && cp /usr/lib/x86_64-linux-gnu/libz.a _bin/
  - qmake CONFIG+=release PREFIX=/usr
  - make -j$(nproc)
  - mkdir -p appdir/usr/bin && cp _bin/Guitar appdir/usr/bin/guitar && strip appdir/usr/bin/guitar && chmod a+x appdir/usr/bin/guitar
  - mkdir -p appdir/usr/share/icons/hicolor/scalable/apps && cp LinuxDesktop/Guitar.svg appdir/usr/share/icons/hicolor/scalable/apps/guitar.svg
  - mkdir -p appdir/usr/share/applications && cp LinuxDesktop/guitar.desktop appdir/usr/share/applications/
  - mkdir -p appdir/usr/share/metainfo && cp LinuxDesktop/guitar.appdata.xml appdir/usr/share/metainfo/
  - linuxdeployqt appdir/usr/share/applications/*.desktop -appimage

after_success:
  - ./packaging/continuous-x86_64/upload.sh Guitar*.AppImage*
  
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
